version: "3.10"
services:
  llm_serve:
    build: .
    image: llm_web_serve
    restart: always
    command:
      - /bin/sh
      - -c
      - "gunicorn -t 120 -w 4 -b 0.0.0.0:96 'flaskr:app'"
    ports:
      - "5002:96"
    environment:
      - PYTHONUNBUFFERED=1
    container_name: "llm_web_serve"
    networks:
      - app_net
networks:
  app_net:
